create table fichiers_cv
(
    id                 bigint generated by default as identity,
    created_at         timestamp(6),
    data               bytea,
    filename           varchar(255),
    status             varchar(255) not null
        constraint fichiers_cv_status_check
            check ((status)::text = ANY
                   ((ARRAY ['WAITING'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying, 'DELETED'::character varying])::text[])),
    status_description varchar(255),
    updated_at         timestamp(6),
    etudiant_id        bigint       not null
        constraint fk6maefy1xvdyu0ex7mmyttfw5p
            references ??? (),
    primary key ()
)
    using ???;

alter table fichiers_cv
    owner to postgres;

create unique index fichiers_cv_pkey
    on fichiers_cv using ??? (id);

