create table offre_stage
(
    format          varchar(31) not null,
    id              bigint generated by default as identity,
    created_at      timestamp(6),
    data            bytea,
    filename        varchar(255),
    updated_at      timestamp(6),
    description     varchar(255),
    email           varchar(255),
    employer_name   varchar(255),
    entreprise_name varchar(255),
    location        varchar(255),
    salary          varchar(255),
    title           varchar(255),
    website         varchar(255),
    primary key ()
)
    using ???;

alter table offre_stage
    owner to postgres;

create unique index offre_stage_pkey
    on offre_stage using ??? (id);

