create table utilisateur
(
    type                varchar(31)  not null,
    id                  bigint generated by default as identity,
    created_at          timestamp(6),
    email               varchar(255) not null,
    password            varchar(255) not null,
    role                varchar(255) not null
        constraint utilisateur_role_check
            check ((role)::text = ANY
                   ((ARRAY ['GESTIONNAIRE_STAGE'::character varying, 'ETUDIANT'::character varying, 'EMPLOYEUR'::character varying, 'ENSEIGNANT'::character varying])::text[])),
    nom                 varchar(255) not null,
    numero_de_telephone varchar(255) not null,
    prenom              varchar(255) not null,
    updated_at          timestamp(6),
    nom_organisation    varchar(255),
    programme           varchar(255)
        constraint utilisateur_programme_check
            check ((programme)::text = ANY
                   ((ARRAY ['TECHNIQUE_INFORMATIQUE'::character varying, 'GENIE_LOGICIEL'::character varying, 'RESEAU_TELECOMMUNICATION'::character varying])::text[])),
    primary key (),
    constraint ukrma38wvnqfaf66vvmi57c71lo
        unique ()
)
    using ???;

alter table utilisateur
    owner to postgres;

create unique index utilisateur_pkey
    on utilisateur using ??? (id);

create unique index ukrma38wvnqfaf66vvmi57c71lo
    on utilisateur using ??? (email);

