version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    command: bash -c "[ ! -d /var/lib/postgresql/data/pg_tblspc ] && mkdir /var/lib/postgresql/data/pg_tblspc; exec docker-entrypoint.sh postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./projet_local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./projet_pgadmin-data:/var/lib/pgadmin
    user: "${UID}:${GID}"